---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_osx: yes

dotfiles_repo: https://github.com/armand1m/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Projects/Personal/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .gitconfig
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - dockutil
  - autoconf
  - bash-completion
  - go
  - gpg
  - iperf
  - libevent
  - sqlite
  - nmap
  - node
  - openssl
  - wrk

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - dropbox
  - google-chrome
  - firefox
  - visual-studio-code
  - telegram
  - spotify
  - virtualbox

# See `geerlingguy.mas` role documentation for usage instructions.
# TODO: See how to override mas_email and mas_password without
# commiting into version control before using this
#
# mas_installed_apps:
#   - { id: 443987910, name: "1Password" }
#   - { id: 497799835, name: "Xcode" }

mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
